[package]
name = "spotify_cli"
version = "0.1.0"
edition = "2021"
description = "Cliente de linha de comando para o Spotify para tocar músicas"
license = "MIT"
authors = ["Gabriel Pelizzaro Pereira <gabrielpelizzaro@gmail.com>"]

[dependencies]

[build-dependencies]
cargo-deb = "^1.43.1"